### ISSUE TITLE
How to get single value from response

### ISSUE THREAD

**Issue by tejas-ebizz** [zerobounce/zero-bounce-ios-sdk#1]
let email = "test@gmali.com"   // The email address you want to validate
    let ipAddress = ""     // The IP Address the email signed up from (Optional)

    ZeroBounceSDK.shared.validate(email, ipAddress) { (result) in
     switch (result) {
     case .Success(let response):
         NSLog("validate success response=\(response)")
         break;
     case .Failure(let error):
         NSLog("validate failure error=\(String(describing: error))")
         switch (error) {
         case ZBError.notInitialized:

            break;
        default:
            break;
        }
        break;
    }
    }

using this code I am getting value in 'response' variable like as follows, and response type is ZBValidateResponse.

validate success response=ZBValidateResponse(address: Optional("test@gmali.com"), status: Optional(ZeroBounceSDK.ZBValidateStatus.invalid), subStatus: Optional(ZeroBounceSDK.ZBValidateSubStatus.possibleTypo), account: Optional("test"), domain: Optional("gmali.com"), didYouMean: Optional("test@gmail.com"), domainAgeDays: Optional("18702"), freeEmail: false, mxFound: false, mxRecord: nil, smtpProvider: Optional(""), firstName: nil, lastName: nil, gender: nil, city: nil, region: nil, zipCode: nil, country: nil, processedAt: Optional("2021-03-16 05:35:21.874"), error: nil)

now my question is how can I get value of 'stars' from this response ?

**Comment by iliescu-Andrei** [comment]
Hi @tejas-ebizz, 
After the latest release, you can now access the response values (e.g. `response.address`).
More examples can be found in the Sample App.
